// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CommentInput struct {
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
	Timestamp time.Time `json:"timestamp"`
	Content   string    `json:"content"`
}

type Mutation struct {
}

type PostInput struct {
	UserID    int       `json:"userID"`
	Content   string    `json:"content"`
	Timestamp time.Time `json:"timestamp"`
	IsOpen    bool      `json:"isOpen"`
}

type Query struct {
}

type RepCommentInput struct {
	PostID    int       `json:"postID"`
	UserID    int       `json:"userID"`
	ParentID  int       `json:"parentID"`
	Timestamp time.Time `json:"timestamp"`
	Content   string    `json:"content"`
}

type Subscription struct {
}
