repository_type: "postgres"

data_base:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"

http_server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s

log:
  level: "INFO"
  path: "./logfile.json"
  lumberjack:
    max_size: 100
    max_age: 30
    max_backups: 5
    local_time: true
    compress: true

shutdown_timeout: 60s
